services:
  web:
    build: .
    container_name: photoshare_web
    image: py-web-team-project-web:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: 
      - .env
    # depends_on:
    #   - redis
    networks:
      - app_network
   
  # db:
  #   image: postgres:15
  #   restart: always
  #   container_name: postgres_container
  #   env_file:
  #     - .env
  #   ports:
  #     - "${PG_PORT:-5432}:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - app_network
  #   healthcheck:  
  #     test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # redis:
  #   image: redis:latest
  #   container_name: redis_container
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge

# volumes:
  # postgres-data:
  # redis-data: