services:
  web:
    image: py-web-team-project-web:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
  
  db:
    image: postgres:15
    restart: always
    env_file: .env         
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  default:
    driver: bridge