"""fix role user nullable=False

Revision ID: a36d0ba96bf1
Revises: 0b5fa8e9a66a
Create Date: 2025-02-18 11:56:45.943699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a36d0ba96bf1'
down_revision: Union[str, None] = '0b5fa8e9a66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='roleset'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='roleset'),
               nullable=True)
    # ### end Alembic commands ###
