"""Add public_id to Image

Revision ID: e6b6c099b034
Revises: 25a7eb98b3e7
Create Date: 2025-02-19 16:08:10.236139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b6c099b034'
down_revision: Union[str, None] = '25a7eb98b3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('public_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'images', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_column('images', 'public_id')
    # ### end Alembic commands ###
